### PR TITLE
Fix issue with encoding using user defined prediction structure config

### LINKED ISSUE #1567: Custom prediction structure not working
**Command:**  `SvtAv1EncApp -i input.y4m  --keyint 16 --hierarchical-levels 3  --pred-struct-file Config/PredStruct_level3.cfg  -b output.ivf`

**Error Message**: (Error: `Encoding          Error: can't find ref frame in dpb list0`) 

**Log**:
```
SVT [version]:  SVT-AV1 Encoder Lib v0.8.5-71-g2936d57
SVT [build]  :  GCC 5.4.0 20160609       64 bit
LIB Build date: Nov  9 2020 10:41:02
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 46
[asm level on system : up to avx2]
[asm level selected : up to avx2]
------------------------------------------- 
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: Preset                                                    : 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 30 / 1 / 17 / 2
SVT [config]: HierarchicalLevels  / PredStructure                               : 3 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 16 / 0 
------------------------------------------- 
Encoding          Error: can't find ref frame in dpb list0
```

The same command with July 1, 2020 build works: 
```
-------------------------------------------
SVT [version]:  SVT-AV1 Encoder Lib v0.8.4
SVT [build]  :  GCC 5.4.0 20160609       64 bit
LIB Build date: Jul  1 2020 12:33:37
-------------------------------------------
```

### PR DESCRIPTION
**Pull request by kedartatwawadi**
# Description
Encoding using user defined custom prediction structure was not working. The small bug fix resolves this issue

The issue seems to have crept in at commit id: a0f233f6ba5d173fc8e258ded045fb0d75074747 
(suggest adding a test for the user defined config to avoid such issues in the future) 

# Issue

Fixes #1567 

# Author(s)
@kedartatwawadi 

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by paulsgh** [comment]
Tested a mix of clips comprised of different resolutions and bit depths.
This PR is lossless.

| | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M8 - 8bit - 2pass - VBR| -0.09% | 0.00% | -0.06%
M8 - 10bit - 2pass - VBR| -0.05% | 0.00% | -0.02%
M0 - 8bit - 2pass| 0.02% | 0.00% | -1.16%
M0 - 10bit - 2pass| -0.04% | 0.00% | 0.06%
M0 - 8bit - 1pass| 0.07% | 0.00% | 0.02%
M4 - 8bit - 1pass| -0.03% | 0.00% | 0.00%
M8 - 8bit - 1pass| 0.67% | 0.00% | 0.02%
M0 - 10bit - 1pass| -0.01% | 0.00% | -0.02%
M4 - 10bit - 1pass| 0.39% | 0.00% | 0.00%
M8 - 10bit - 1pass| 0.00% | 0.00% | -0.02%

I have also verified that this PR fixes issue #1567.

**Comment by hassount** [comment]
@bzhutencent could you please take a quick look at this ?

File: Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c [hunk 1]
```diff
@@ -3231,7 +3231,11 @@ static EbErrorType av1_generate_rps_info_from_user_config(
...
         uint8_t ref_idx = 0;
         for (ref_idx = LAST; ref_idx < LAST + picture_control_set_ptr->ref_list0_count; ++ref_idx) {
-            uint64_t ref_poc = picture_control_set_ptr->picture_number;
+            uint64_t ref_poc = picture_control_set_ptr->picture_number - pred_position_ptr->ref_list0.reference_list[ref_idx-LAST];
+            if (picture_control_set_ptr->is_overlay) {
+                ref_poc = picture_control_set_ptr->picture_number;
+            }
+
             if (picture_control_set_ptr->is_overlay)
                 ref_poc -= pred_position_ptr->ref_list0.reference_list[ref_idx - LAST];
```
Comment (elintencent) [inline Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c:3240]: Then should these two lines be removed?

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c:3240]: @kedartatwawadi can you please address this comment ?

Comment (kedartatwawadi) [reply Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c]: Thanks @elintencent, sorry missed removing it out. 
@hassount ll clean it up

Comment (kedartatwawadi) [reply Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c]: The comment has been addressed now

**Comment by elintencent** [comment]
lgtm

**Comment by hassount** [comment]
@kedartatwawadi  thank you for the PR, can you please let me know when you have signed the appropriate CLA as per: https://github.com/AOMediaCodec/SVT-AV1#contributor-agreement

**Comment by kedartatwawadi** [comment]
@hassount Thanks! I have signed the CLA.
